#!/usr/bin/env python3
"""Attribution-hygiene gate — CLAUDE.md §6.

Greps tracked, text-diffable files for forbidden generator/tool-attribution
strings. Runs at every UI gate per docs/UI-SPEC.md and as a pre-commit hook
so a stray "Built with", "Generated by", commit co-authorship trailer, etc.
never lands in the repo in the first place.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

FORBIDDEN_PATTERNS = [
    r"(?i)\bbuilt with\b",
    r"(?i)\bgenerated by\b",
    r"(?i)\bgenerated with\b",
    r"(?i)\bpowered by\b(?!\s+(postgres|clickhouse|nats|valkey|seaweedfs))",
    r"(?i)\bmade with ai\b",
    r"(?i)co-authored-by:\s*claude",
    r"(?i)<meta\s+name=[\"']generator[\"']",
    r"claude\.ai/code",
    r"anthropic\.com",
]

# Paths this repo legitimately mentions Claude Code / Anthropic in — internal
# dev tooling, not product surface or attribution. Excluded from the scan.
EXEMPT_PREFIXES = (
    ".claude/",
    "CLAUDE.md",
    "scripts/check_no_watermarks.py",  # this file, which must contain the patterns above
)


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
        cwd=ROOT, capture_output=True, text=True, check=False,
    ).stdout.splitlines()
    if not out:
        out = subprocess.run(
            ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=False,
        ).stdout.splitlines()
    return [f for f in out if not f.startswith(EXEMPT_PREFIXES)]


def main() -> int:
    violations: list[str] = []
    compiled = [re.compile(p) for p in FORBIDDEN_PATTERNS]
    for rel in tracked_files():
        path = ROOT / rel
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for pattern in compiled:
            for m in pattern.finditer(text):
                line_no = text.count("\n", 0, m.start()) + 1
                violations.append(f"{rel}:{line_no}: matched /{pattern.pattern}/")

    if violations:
        print("WATERMARK GATE: FAIL\n")
        for v in violations:
            print(f"  - {v}")
        return 1

    print("WATERMARK GATE: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
